version: '3.8'

services:
  oap:
    image: apache/skywalking-oap-server:8.3.0-es7
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 127.0.0.1 11800" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SW_STORAGE: h2

  ui:
    image: apache/skywalking-ui:8.3.0
    container_name: ui
    depends_on:
      oap:
        condition: service_healthy
    links:
      - oap
    ports:
      - "8080:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800
